language: php

php:
  - 5.6

matrix:
  allow_failures:
    - php: 7

services:
  - redis-server

before_script:
  - pecl install redis
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar self-update
  - php composer.phar install --dev --no-interaction

script:
  - mkdir -p build/logs
  - phpunit -c phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls -v